solved
mate-academy/react_todo-app-loading-todos pull request #1461
Opened 2024-08-05 21:53 UTC by DanielLinker17

https://DanielLinker17.github.io/react_todo-app-loading-todos/

2024-08-05 21:55 UTC, DanielLinker17 commented
Went a bit too far with a solution and accidentally implemented second part of the task

2024-08-05 23:45 UTC, GUSILLUS requested changes
GJ!

2024-08-05 23:45 UTC, GUSILLUS commented on src/App.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
Consider creating enum for you filters state

2024-08-05 23:45 UTC, GUSILLUS commented on src/App.tsx
> +        )}
Do you want to hide only the the footer if you have no todos?

2024-08-05 23:45 UTC, GUSILLUS commented on src/Components/Footer/Footer.tsx
> +        </a>
Consider using `Object.values(your enum)` and `map()` method

2024-08-05 23:45 UTC, GUSILLUS commented on src/Components/Header/Header.tsx
> +      <form onSubmit={addToDo}>
space

2024-08-05 23:45 UTC, GUSILLUS commented on src/Components/Todo/TodoItem.tsx
> +          id={`todoStatus-${todo.id}`}
Consider using destruction assignment for `todo` object

2024-08-05 23:45 UTC, GUSILLUS commented on src/Components/Todo/TodoItem.tsx
> +            onDoubleClick={() => setIsEditing(true)}
Consider creating handler function

2024-08-15 06:45 UTC, volodymyr-soltys97 requested changes
Almost done!

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/App.tsx
> +  const areAllTodosCompleted = todos.every(todo => todo.completed === true);
```suggestion
  const areAllTodosCompleted = todos.every(todo => todo.completed);
```

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/App.tsx
> +      case 'active':
Use enum here instead of 'completed', 'active'

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/App.tsx
> +        {todos.length !== 0 && (
```suggestion
        {!!todos.length && (
```

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/Components/ErrorMessage/ErrorMessage.tsx
> +    'has-text-weight-normal': true,
```suggestion
  const messageClass = classNames('
    notification
    is-danger
    is-light
    has-text-weight-normal
  ', {
```

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/Components/Footer/Footer.tsx
> +            className={`filter__link ${filter === filterValue ? 'selected' : ''}`}
Use the classnames library rules for add classes with condition

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/Components/Header/Header.tsx
> +        className={`todoapp__toggle-all ${areAllTodosCompleted ? 'active' : ''}`}
The same here

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/Components/Todo/TodoItem.tsx
> +    <div data-cy="Todo" className={`todo ${completed ? 'completed' : ''}`}>
The same

2024-08-15 06:45 UTC, volodymyr-soltys97 commented on src/Components/Todo/TodoItem.tsx
> +            onDoubleClick={() => handleTriggerEdit()}
```suggestion
            onDoubleClick={handleTriggerEdit}
```

2024-08-16 11:06 UTC, volodymyr-soltys97 approved these changes
Great work! 🔥

2025-07-22 23:24 UTC, closed without merging