Develop
mate-academy/react_todo-app-loading-todos pull request #1521
Opened 2024-09-25 13:51 UTC by Natallia3105

https://Natallia3105.github.io/react_todo-app-loading-todos/

2024-09-25 13:59 UTC, anastasiiavorobiova requested changes
Great start! Consider splitting the App component into smaller components. 
The layout looks a bit broken 
<img width="252" alt="Screenshot 2024-09-25 at 16 55 49" src="https://github.com/user-attachments/assets/4e10e4c0-4017-4770-8cd8-00e36fb35179">
Consider fixing it

2024-09-26 11:10 UTC, lerastarynets requested changes
Well done
Now, pls try to pass all tests, if your tests pass locally, but you encounter a problem in server tests, pls attach a screen of all local tests passing

2024-09-26 11:42 UTC, Natallia3105 commented
but in the first part of the task there are only 36 tests to pass or am I wrong?

2024-09-26 11:46 UTC, anastasiiavorobiova approved these changes
Great work!

2024-09-26 11:46 UTC, anastasiiavorobiova commented on src/api/todos.ts
> +// };
```suggestion

```

2025-01-24 13:13 UTC, closed without merging