remaked
mate-academy/react_todo-app-loading-todos pull request #158
Opened 2022-12-10 23:39 UTC by savchuksavchuk

[DEMO LINK](https://savchuksavchuk.github.io/react_todo-app-loading-todos/)

2022-12-12 09:46 UTC, vlad-demchuk requested changes

2022-12-12 09:46 UTC, vlad-demchuk commented on src/App.tsx
> +          return true;
use `enum` for status

2022-12-12 09:46 UTC, vlad-demchuk commented on src/App.tsx
> +  const [error, setError] = useState('');
use more meaningful name for `error`.  eg `errorMessage`

2022-12-12 09:46 UTC, vlad-demchuk commented on src/App.tsx
> +    setIsLoaded(true);
use `finally`

2022-12-12 09:46 UTC, vlad-demchuk commented on src/components/TodoItem.tsx
> +          </form> */}
remove comments

2022-12-13 16:45 UTC, loralevitska approved these changes
Good job!

try to fix such errors) 
![image](https://user-images.githubusercontent.com/70009205/207393234-06569a8b-8d81-41c7-9d9c-6ba8ff3d9ef5.png)

2024-12-28 11:14 UTC, closed without merging