filter by status, decompose, rendered list were created
mate-academy/react_todo-app-loading-todos pull request #168
Opened 2022-12-12 20:39 UTC by mitattt

[DEMO LINK](https://mitattt.github.io/react_todo-app-loading-todos/)

2022-12-12 21:01 UTC, iryna-lelyk approved these changes
Great solution 💪

2022-12-13 12:18 UTC, Olexandr6 requested changes
Almost done🔥🔥🔥🔥🔥
Now, let's work on improvements:

2022-12-13 12:18 UTC, Olexandr6 commented on src/App.tsx
> +      const todosFromServer = await getTodos(user?.id || 0);
```suggestion
      const todosFromServer = await getTodos(user?.id || 1);
```

2022-12-13 12:18 UTC, Olexandr6 commented on src/App.tsx
>    const newTodoField = useRef<HTMLInputElement>(null);
Let's move this useRef with the corresponding `useEffect` to the `Header` component. Looks like you need this logic only in `Header` component, not in the `App.tsx`

2022-12-13 12:18 UTC, Olexandr6 commented on src/components/TodoList.tsx
> +  }, [todos, status]);
Move this logic directly to `useMemo`, you don't need `useCallback` here

2022-12-13 15:36 UTC, Olexandr6 approved these changes

2025-01-16 21:02 UTC, closed without merging