solution
mate-academy/react_todo-app-loading-todos pull request #231
Opened 2023-01-22 12:59 UTC by official-artem

[DEMO LINK](https://official-artem.github.io/react_todo-app-loading-todos/)

2023-01-23 17:59 UTC, Nazar-Brunarskyi approved these changes
nice)

2023-01-24 14:01 UTC, Ihor-Karpyn requested changes
Completed filter doesn't work on the demo link

2023-01-24 14:01 UTC, Ihor-Karpyn commented on src/App.tsx
> +        {isLoaded && <Footer onSelectFilter={handleClickFilter} />}
I think the footer always should be visible, u could disable the button when todos are loaded

2023-01-24 14:01 UTC, Ihor-Karpyn commented on src/components/ErrorMessage/ErrorMessage.tsx
> +      </div>
Do not leave the comments

2023-01-25 09:44 UTC, Ihor-Karpyn approved these changes

2026-03-01 23:25 UTC, closed without merging