Develop
mate-academy/react_todo-app-loading-todos pull request #266
Opened 2023-01-26 00:42 UTC by panianchuk

https://panianchuk.github.io/react_todo-app-loading-todos/

2023-01-26 19:57 UTC, SanyaBratashchuk requested changes

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/App.tsx
> +import { Footer } from './components/Footer';
Create index.ts file in components folder and export each component from it

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/App.tsx
> +import { Error } from './types/Error';
The same with types. Create index.ts file

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/App.tsx
>    const user = useContext(AuthContext);
Move useContext(AuthContext) to custom useAuth hook

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/App.tsx
> +  const [isHidden, setIsHidden] = useState(true);
What is hidden? Todos? Filters? Specify that

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/App.tsx
> +  const handleAddToto = (titleTodo: string) => {
```suggestion
  const handleAddTodo = (titleTodo: string) => {
```

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/api/filter.ts
> +    case completed:
```suggestion
    case Filter.active:
```

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/api/filter.ts
> +    case completed:
Fix it everywhere

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/api/filter.ts
> +const { active, completed } = Filter;
```suggestion
```

2023-01-26 19:57 UTC, SanyaBratashchuk commented on src/components/ErrorNotification.tsx
> +  setIsHidden: (isHidden: boolean) => void;
```suggestion
  setIsHidden: Dispatch<SetStateAction<boolean>>;
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der requested changes
Hi, there is more comments from me)

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/Header.tsx
> +export const Header: React.FC<Props> = ({
if you pass ref - you have to wrap your component with `forwardRef()` and take it as second argument 
```suggestion
export const Header: React.FC<Props> = forwardRef((props, passedRef) => ...jsx)
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/App.tsx
> +
Why just don't set `autofocus `attribute for input?

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/App.tsx
> +        }, 3000);
Duplicated code from 41-44 lines, it is better to move these commands into separated function

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/App.tsx
> +          handleAddToto={handleAddToto}
props handler callback should be named as on...: onChange, onClick, onAddTodo.. etc
```suggestion
         onAddToto={handleAddToto}
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoItem.tsx
> +export const TodoItem: React.FC<Props> = ({ todo }) => {
```suggestion
export const TodoItem: React.FC<Props> = ({ todo: { completed , ...} }) => {
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoList.tsx
> +      ))}
```suggestion
      {todos.map((todo) => (
        <TodoItem
          key={todo.id}
          todo={todo}
        />
      ))}
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/types/Error.ts
> +export enum Error {
```suggestion
export enum ErrorTypes {
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/types/Error.ts
> +  add = 'Unable to add a todo',
first letter of enum keys has to be uppercase
```suggestion
  Loading = 'Unable to load a todos',
  Add = 'Unable to add a todo',
```

2023-01-28 15:11 UTC, Volodymyr-Melnyk-Fron10der commented on src/types/Filter.ts
> +}
First letter - uppercase

2023-01-29 09:16 UTC, qoa11a approved these changes

2023-12-29 10:39 UTC, closed without merging