solution: implement add, error, filter
mate-academy/react_todo-app-loading-todos pull request #413
Opened 2023-04-10 07:04 UTC by vadym4che

[DEMO LINK](https://vadym4che.github.io/react_todo-app-loading-todos/)

2023-04-10 12:23 UTC, Bogdan-Mykhailov requested changes
good job, but in readme file was said that no need to implement extra logic, also please separate your code to different components

2023-04-10 12:23 UTC, Bogdan-Mykhailov commented on src/App.tsx
> +  };
you don't need that here and also in the next hw

2023-04-10 12:23 UTC, Bogdan-Mykhailov commented on src/App.tsx
>          </header>
all inside header should be different component

2023-04-10 12:23 UTC, Bogdan-Mykhailov commented on src/App.tsx
>            </nav>
also footer should be different component

2023-04-10 12:23 UTC, Bogdan-Mykhailov commented on src/App.tsx
> +          {todosToShow.map(todo => <TodoItem key={todo.id} todo={todo} />)}
also for correct structure of your project need to add TodoList component and inside that component you can map your TodoListItems

2023-04-10 12:23 UTC, Bogdan-Mykhailov commented on src/api/todos.ts
> +};
in this task we don't need to add that logic

2023-04-13 16:19 UTC, Andr1yK approved these changes

2024-12-09 10:33 UTC, closed without merging