solution
mate-academy/react_todo-app-loading-todos pull request #642
Opened 2023-07-10 11:12 UTC by MaxSchmide

[DEMO LINK](https://maxschmide.github.io/react_todo-app-loading-todos/)

2023-07-11 15:57 UTC, ollavka approved these changes

2023-07-17 13:23 UTC, anstsot requested changes
Create the component for errors as said in the task, please
![image](https://github.com/mate-academy/react_todo-app-loading-todos/assets/22824431/dc3a9ff8-db4f-439d-822e-6aa5a00ba120)

2023-07-17 13:23 UTC, anstsot commented on src/App.tsx
> +          </footer>
create separate `Footer` component

2023-07-17 13:23 UTC, anstsot commented on src/App.tsx
> +            <div
create separate `TodoItem` component

2023-07-25 08:07 UTC, anstsot requested changes
Try to set error message on load

2023-07-25 08:07 UTC, anstsot commented on src/App.tsx
> +        throw error;
```suggestion
        setErrorMessage(error);
```

2023-07-25 08:26 UTC, anstsot requested changes
Let's add few more fixes and reduce the number of state variables

2023-07-25 08:26 UTC, anstsot commented on src/App.tsx
> +  const [completedTodos, setCompletedTodos] = useState<Todo[]>([]);
the variable `completedTodos` can be calculated based on `todosContainer` by using `useMemo` hook

2023-07-25 08:26 UTC, anstsot commented on src/App.tsx
> +  const [todos, setTodos] = useState<Todo[]>([]);
the variable `todos` can be calculated based on `todosContainer` and `selectedStatus` by using `useMemo` hook

2023-07-28 08:25 UTC, anstsot requested changes
There is still a bug with an error showing. maybe you forgot to redeploy?

2023-07-28 08:25 UTC, anstsot commented on src/App.tsx
> +            <TodoItem todo={todo} />
don't forget about `key`

2023-07-31 07:16 UTC, anstsot approved these changes

2023-10-20 18:17 UTC, closed without merging