Task is done
mate-academy/react_todo-app-loading-todos pull request #750
Opened 2023-08-17 16:50 UTC by Konsttantin

[DEMO LINK](https://Konsttantin.github.io/react_todo-app-loading-todos/)

2023-08-17 17:19 UTC, etojeDenys requested changes

2023-08-17 17:19 UTC, etojeDenys commented on src/App.tsx
> +        return [...todos].filter(todo => !todo.completed);
```suggestion
        return todos.filter(todo => !todo.completed);
```
filter create the new array so we don't need to make copy here

2023-08-17 17:19 UTC, etojeDenys commented on src/components/ErrorMessage/ErrorMessage.tsx
> +      'has-text-weight-normal',
join it all in one string

2023-08-21 06:44 UTC, maxim2310 approved these changes
Good work!!!

2025-01-19 15:37 UTC, closed without merging