Solution
mate-academy/react_todo-app-loading-todos pull request #980
Opened 2023-11-18 16:41 UTC by NasyTheSlayer

[DEMO LINK](https://NasyTheSlayer.github.io/react_todo-app-loading-todos/

2023-11-18 16:53 UTC, Esceype requested changes
GJ!
Need to make some fixes in edit mode:
- after edit with spaces it shows okay, but if open the same todo after editing it saves the spaces in end on in start, you need to trim it before save
-  if I save empty todo I see the placeholder, but it doesn`t work, if I try to save empty todo it save previous value and not delete it.

2023-11-19 07:51 UTC, Andriy-Shymkiv approved these changes
good job. left some comments. approved in advance

2023-11-19 07:51 UTC, Andriy-Shymkiv commented on src/components/Eror/Error.tsx
> +    isErrorHidden = false;
create state for this

2023-11-19 07:51 UTC, Andriy-Shymkiv commented on src/components/Footer/Footer.tsx
> +  const isVisibleCrealButton = todos.some(todo => todo.completed);
what is `Creal`?

2023-11-19 07:51 UTC, Andriy-Shymkiv commented on src/utils/getNumberActiveTodo.tsx
> +};
```suggestion
export const getActiveTodosLength = (todos: Todo[]) => {
  return todos.filter(todo => !todo.completed).length
};
```

2024-09-29 08:37 UTC, closed without merging